
import { GoogleGenAI } from "@google/genai";

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY;

let ai: GoogleGenAI | null = null;
if (API_KEY) {
    ai = new GoogleGenAI({ apiKey: API_KEY });
} else {
    console.warn("Gemini API key not found. AI features will be disabled.");
}

export const isAiAvailable = (): boolean => !!ai;

type ChatHistory = { role: 'user' | 'model'; parts: { text: string }[] }[];

export const getChatbotResponse = async (prompt: string, history: ChatHistory): Promise<string> => {
    if (!ai) {
        return "AI service is unavailable. Please configure the API key.";
    }
    try {
        const chat = ai.chats.create({
            model: 'gemini-2.5-flash',
            history: history,
            config: {
                systemInstruction: "You are a friendly and helpful virtual assistant for Newark Hospital. Your role is to answer general questions about the hospital, such as location, visiting hours, and services offered. You must not provide any medical advice, diagnoses, or treatment recommendations. If a user asks for medical advice, you must politely decline and advise them to consult with a doctor or use the hospital's Symptom Checker tool for informational purposes. Keep your answers concise and helpful."
            }
        });
        const response = await chat.sendMessage({ message: prompt });
        return response.text;
    } catch (error) {
        console.error("Gemini API Error in getChatbotResponse:", error instanceof Error ? error.message : error);
        return "I'm sorry, I'm having trouble connecting right now. Please try again later.";
    }
};

export const getSymptomAnalysis = async (symptoms: string): Promise<string> => {
    if (!ai) {
        return "AI service is unavailable. Please configure the API key.";
    }
    try {
        const prompt = `
            Analyze the following symptoms and provide a potential analysis for informational purposes only. The user is on a hospital website. Format the response using markdown.

            **IMPORTANT DISCLAIMER (MUST be included VERBATIM at the beginning of the response):**
            "**Disclaimer:** This analysis is generated by an AI and is for informational purposes only. It is not a medical diagnosis. Please consult with a qualified healthcare professional for any health concerns or before making any medical decisions."

            **User's Symptoms:**
            "${symptoms}"

            **Instructions:**
            1.  Start with the exact disclaimer above.
            2.  Create a markdown heading '### Possible Conditions'. Under it, list 2-3 potential conditions, from most likely to less likely.
            3.  For each condition, provide a brief, easy-to-under-know description.
            4.  Create a markdown heading '### Recommended Next Steps'. Under it, provide a list of general, safe next steps, such as "Rest and stay hydrated," "Monitor your symptoms," and most importantly, "Schedule an appointment with a doctor for an accurate diagnosis."
            5.  Do not use alarming language. The tone should be helpful, cautious, and professional.
        `;

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
        });
        return response.text;
    } catch (error) {
        console.error("Gemini API Error in getSymptomAnalysis:", error instanceof Error ? error.message : error);
        return "I'm sorry, I was unable to analyze the symptoms. Please try again or consult a doctor directly.";
    }
};